name: CI(nightly)

on:
    # manual trigger
    workflow_dispatch:
    # every night
    schedule:
        - cron: '0 0 * * *'
    push:
        branches:
            - main

env:
  OHOS_NDK_HOME: /opt/command-line-tools/sdk/default/openharmony
  DEVECO_SDK_HOME: /opt/command-line-tools/sdk

jobs:
    build-apk:
        # matrix features 1.cn and 2.global
        strategy:
            matrix:
                features:
                    - cn
                    - global
        runs-on: ubuntu-22.04
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            repository: kingtous/remote_unlock_reborn
            token: ${{ secrets.GH_PAT }}

        - name: Setup OpenHarmony SDK
          shell: bash
          run: |
            pushd /opt

            curl -sSOL https://github.com/Kingtous/archives/releases/download/hmos-cli-sdk-5.0.5.300/hmos-cli-sdk-5.0.5.300.zip
            curl -sSOL https://github.com/Kingtous/archives/releases/download/hmos-cli-sdk-5.0.5.300/hmos-cli-sdk-5.0.5.300.z01
            curl -sSOL https://github.com/Kingtous/archives/releases/download/hmos-cli-sdk-5.0.5.300/hmos-cli-sdk-5.0.5.300.z02

            zip -q -F hmos-cli-sdk-5.0.5.300.zip --out temp_hmos-cli-sdk-5.0.5.300.zip

            rm hmos-cli-sdk-5.0.5.300*

            ls -l /opt

            unzip -qq temp_hmos-cli-sdk-5.0.5.300.zip
            rm temp_hmos-cli-sdk-5.0.5.300.zip

            echo '/opt/command-line-tools/tool/node/bin' >> $GITHUB_PATH
            echo '/opt/command-line-tools/hvigor/bin' >> $GITHUB_PATH
            echo '/opt/command-line-tools/ohpm/bin' >> $GITHUB_PATH
            echo '/opt/command-line-tools/bin' >> $GITHUB_PATH

            node --version
            ohpm --version

        - uses: actions/setup-java@v4
          with:
            distribution: 'adopt' # See 'Supported distributions' for available options
            java-version: '19'

        - uses: nttld/setup-ndk@v1
          id: setup_ndk
          with:
            ndk-version: r25c
            add-to-path: true

        - name: Set up custom flutter and add to github action PATH
          shell: bash
          run: |
            pushd /opt
            git clone https://gitee.com/harmonycommando_flutter/flutter.git
            pushd flutter
            git checkout oh-3.22.3 || true
            echo '/opt/flutter/bin' >> $GITHUB_PATH

        - name: Print version
          shell: bash
          run: |
            flutter --version || true
            flutter doctor -v || true
            java --version || true

        - name: Set up Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
            profile: minimal
            target: aarch64-linux-android
        - name: Setup Rust Android
          shell: bash
          run: |
            rustup target add aarch64-linux-android
            rustup target add armv7-linux-androideabi
            rustup target add i686-linux-android
            rustup target add x86_64-linux-android
        - name: Build
          shell: bash
          env:
            ANDROID_NDK_HOME: ${{ steps.setup_ndk.outputs.ndk-path }}
            APP_RUST_FEATURES: ${{ matrix.features }}
          run: |
            pushd client
            flutter pub get
            flutter build apk --target-platform android-arm64,android-arm,android-x64 --split-per-abi --release --flavor ${{ matrix.features }}
            flutter build aab --release

        - name: Rename apk and add features
          shell: bash
          run: |
            pushd client/build/app/outputs/flutter-apk
            # for all files with .apk suffix
            for file in *.apk; do
              # get the file name without extension
              name=$(basename $file .apk)
              # get the file extension
              ext="${file##*.}"
              # get the file name without extension
              name=$(basename $file .apk)
              # get the file extension
              ext="${file##*.}"
              # rename the file to include the feature name
              mv $file $name-${{ matrix.features }}.$ext
            done
            popd

            pushd client/build/app/outputs/bundle/release
            # for all files with .aab suffix
            for file in *.aab; do
              # get the file name without extension
              name=$(basename $file .aab)
              # get the file extension
              ext="${file##*.}"
              # get the file name without extension
              name=$(basename $file .aab)
              # get the file extension
              ext="${file##*.}"
              # rename the file to include the feature name
              mv $file $name-${{ matrix.features }}.$ext
            done
            

        - uses: ncipollo/release-action@v1
          # if: startsWith(github.ref, 'refs/tags/v')
          with:
            tag: nightly
            allowUpdates: true
            artifacts: "client/build/app/outputs/flutter-apk/*.apk"
            token: ${{ secrets.GITHUB_TOKEN }}
            body: body.md
            artifactContentType: "application/vnd.android.package-archive"
        
        - uses: ncipollo/release-action@v1
          # if: startsWith(github.ref, 'refs/tags/v')
          with:
            tag: nightly
            allowUpdates: true
            artifacts: "client/build/app/outputs/bundle/release/*.aab"
            token: ${{ secrets.GITHUB_TOKEN }}
            body: body.md
            artifactContentType: "application/vnd.android.package-archive"

