name: CI(nightly)

on:
    # manual trigger
    workflow_dispatch:
    # every night
    schedule:
        - cron: '0 0 * * *'
jobs:
    build-apk:
        # matrix features 1.cn and 2.global
        strategy:
            matrix:
                features:
                    - cn
                    - global
        runs-on: ubuntu-22.04
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            repository: kingtous/remote_unlock_reborn
            token: ${{ secrets.GH_PAT }}

        - uses: actions/setup-java@v4
          with:
            distribution: 'adopt' # See 'Supported distributions' for available options
            java-version: '19'

        - uses: nttld/setup-ndk@v1
          id: setup_ndk
          with:
            ndk-version: r25c
            add-to-path: true
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.22.0'

        - name: Print version
          shell: bash
          run: |
            flutter --version
            flutter doctor -v
            java --version

        - name: Set up Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
            profile: minimal
            target: aarch64-linux-android
        - name: Setup Rust Android
          shell: bash
          run: |
            rustup target add aarch64-linux-android
            rustup target add armv7-linux-androideabi
            rustup target add i686-linux-android
            rustup target add x86_64-linux-android
        - name: Build
          shell: bash
          env:
            ANDROID_NDK_HOME: ${{ steps.setup_ndk.outputs.ndk-path }}
            APP_RUST_FEATURES: ${{ matrix.features }}
          run: |
            pushd client
            flutter pub get
            flutter build apk --target-platform android-arm64,android-arm,android-x64 --split-per-abi --release
            flutter build aab --release

        - name: Rename apk and add features
          shell: bash
          run: |
            pushd client/build/app/outputs/flutter-apk
            # for all files with .apk suffix
            for file in *.apk; do
              # get the file name without extension
              name=$(basename $file .apk)
              # get the file extension
              ext="${file##*.}"
              # get the file name without extension
              name=$(basename $file .apk)
              # get the file extension
              ext="${file##*.}"
              # rename the file to include the feature name
              mv $file $name-${{ matrix.features }}.$ext
            done
            popd
            pushd client/build/app/outputs/bundle/release
            # for all files with .aab suffix
            for file in *.aab; do
              # get the file name without extension
              name=$(basename $file .aab)
              # get the file extension
              ext="${file##*.}"
              # get the file name without extension
              name=$(basename $file .aab)
              # get the file extension
              ext="${file##*.}"
              # rename the file to include the feature name
              mv $file $name-${{ matrix.features }}.$ext
            done
            

        - uses: ncipollo/release-action@v1
          # if: startsWith(github.ref, 'refs/tags/v')
          with:
            tag: nightly
            allowUpdates: true
            artifacts: "client/build/app/outputs/flutter-apk/*.apk"
            token: ${{ secrets.GITHUB_TOKEN }}
            body: body.md
            artifactContentType: "application/vnd.android.package-archive"
        
        - uses: ncipollo/release-action@v1
          # if: startsWith(github.ref, 'refs/tags/v')
          with:
            tag: nightly
            allowUpdates: true
            artifacts: "client/build/app/outputs/bundle/release/*.aab"
            token: ${{ secrets.GITHUB_TOKEN }}
            body: body.md
            artifactContentType: "application/vnd.android.package-archive"

